# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import json


class Ui_Dialog(object):
    def __init__(self, submit_txt):
        self.submit_txt = submit_txt

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1229, 975)
        Dialog.setStyleSheet("background-color : white;\n")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")

        self.addVitaminAdvice()

        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def addVitaminAdvice(self):
        """
        add corresponding vitamin widgets
        """
        # parse submit_txt
        symptom_ls = [symptom.strip() for symptom in self.submit_txt.split("；")]
        vitamin_symptom_dic = {}
        symptom_vitamin_dic: dict = json.load(open("json/symptom_vitamin.json", "r", encoding="utf-8", errors='ignore'))
        for symptom in symptom_ls:
            if symptom in symptom_vitamin_dic.keys():
                vitamin = symptom_vitamin_dic[symptom]
                if vitamin in vitamin_symptom_dic.keys():
                    vitamin_symptom_dic[vitamin].append(symptom)
                else:
                    vitamin_symptom_dic[vitamin] = [symptom]
        # load advice and warning
        vitamin_advice_dic: dict = json.load(open("json/advise.json", "r", encoding="utf-8", errors='ignore'))
        vitamin_warning_dic: dict = json.load(open("json/warning.json", "r", encoding="utf-8", errors='ignore'))
        # add the corresponding widgets
        for vitamin, symptoms in vitamin_symptom_dic.items():
            tab = QtWidgets.QWidget()
            verticalLayout = QtWidgets.QVBoxLayout(tab)
            verticalLayout.setSpacing(20)
            # main label
            vitamin_lbl = QtWidgets.QLabel(tab)
            font = QtGui.QFont()
            font.setFamily("华文中宋")
            font.setPointSize(20)
            vitamin_lbl.setFont(font)
            vitamin_lbl.setText(vitamin)
            vitamin_lbl.setStyleSheet("padding-top:20px;")
            verticalLayout.addWidget(vitamin_lbl)
            # spacer
            spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
            verticalLayout.addItem(spacerItem)
            # icon 1
            icon1_lbl = QtWidgets.QLabel(tab)
            icon1_lbl.setText("")
            icon1_lbl.setPixmap(QtGui.QPixmap("icons/pic1.png"))
            verticalLayout.addWidget(icon1_lbl)
            # textBrowser1
            textBrowser1 = QtWidgets.QTextBrowser(tab)
            font = QtGui.QFont()
            font.setFamily("华文仿宋")
            font.setPointSize(11)
            textBrowser1.setFont(font)
            textBrowser1.setStyleSheet("border : 0px ;")
            verticalScrollBar1 = QtWidgets.QScrollBar(textBrowser1)
            verticalScrollBar1.setOrientation(QtCore.Qt.Vertical)
            verticalScrollBar1.setStyleSheet(open("styles/vscrollbar_style.qss", "r").read())
            textBrowser1.setVerticalScrollBar(verticalScrollBar1)
            verticalLayout.addWidget(textBrowser1)
            # icon 2
            icon2_lbl = QtWidgets.QLabel(tab)
            icon2_lbl.setText("")
            icon2_lbl.setPixmap(QtGui.QPixmap("icons/pic2.png"))
            verticalLayout.addWidget(icon2_lbl)
            # textBrowser2
            textBrowser2 = QtWidgets.QTextBrowser(tab)
            font = QtGui.QFont()
            font.setFamily("华文仿宋")
            font.setPointSize(11)
            textBrowser2.setFont(font)
            textBrowser2.setStyleSheet("border : 0px ;")
            verticalScrollBar2 = QtWidgets.QScrollBar(textBrowser2)
            verticalScrollBar2.setOrientation(QtCore.Qt.Vertical)
            verticalScrollBar2.setStyleSheet(open("styles/vscrollbar_style.qss", "r").read())
            textBrowser2.setVerticalScrollBar(verticalScrollBar2)
            verticalLayout.addWidget(textBrowser2)
            # icon 3
            icon3_lbl = QtWidgets.QLabel(tab)
            icon3_lbl.setText("")
            icon3_lbl.setPixmap(QtGui.QPixmap("icons/pic3.png"))
            verticalLayout.addWidget(icon3_lbl)
            # textBrowser3
            textBrowser3 = QtWidgets.QTextBrowser(tab)
            font = QtGui.QFont()
            font.setFamily("华文仿宋")
            font.setPointSize(11)
            textBrowser3.setFont(font)
            textBrowser3.setStyleSheet("border : 0px ;")
            verticalScrollBar3 = QtWidgets.QScrollBar(textBrowser3)
            verticalScrollBar3.setOrientation(QtCore.Qt.Vertical)
            verticalScrollBar3.setStyleSheet(open("styles/vscrollbar_style.qss", "r").read())
            textBrowser3.setVerticalScrollBar(verticalScrollBar3)
            verticalLayout.addWidget(textBrowser3)
            # setText
            textBrowser1.setText("；".join(symptoms))
            if vitamin in vitamin_advice_dic:
                textBrowser2.setText(vitamin_advice_dic[vitamin])
            if vitamin in vitamin_warning_dic:
                textBrowser3.setText(vitamin_warning_dic[vitamin])
            self.tabWidget.addTab(tab, "")
            self.tabWidget.setTabText(self.tabWidget.indexOf(tab), vitamin)
            # set stretch
            verticalLayout.setStretch(0, 1)
            verticalLayout.setStretch(1, 1)
            verticalLayout.setStretch(2, 1)
            verticalLayout.setStretch(3, 1)
            verticalLayout.setStretch(4, 1)
            verticalLayout.setStretch(5, 2)
            verticalLayout.setStretch(6, 1)
            verticalLayout.setStretch(7, 8)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowIcon(QtGui.QIcon("icons/icon.png"))
        Dialog.setWindowTitle(_translate("Dialog", "诊断结果"))
